fix: enhance version determination logic and add error handling for empty version

diff --git a/.github/workflows/prepare-tag.yml b/.github/workflows/prepare-tag.yml
--- a/.github/workflows/prepare-tag.yml
+++ b/.github/workflows/prepare-tag.yml
@@ -26,17 +26,29 @@ jobs:
       - name: Determine version
         id: version
         run: |
-          if [ "${{ github.event.inputs.version }}" = "next" ]; then
+          INPUT_VERSION=${{ github.event.inputs.version }} 
+          if [ -z "$INPUT_VERSION" ]; then
+            echo "::info:: No version input provided, defaulting to 'next'."
+            INPUT_VERSION="next"
+          fi
+
+          if [ $INPUT_VERSION = "next" ]; then
             CURR=$(jq -r .version composer.json)
             MAJOR=$(echo $CURR | cut -d. -f1)
             MINOR=$(echo $CURR | cut -d. -f2)
             PATCH=$(echo $CURR | cut -d. -f3)
             NEW_PATCH=$((PATCH+1))
             NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
-            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
+            VERSION="$NEW_VERSION"
           else
-            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
+            VERSION="${{ github.event.inputs.version }}"
           fi
+          
+          if [ -z "$VERSION" ]; then
+            echo "::error::Version is empty. Failing job."
+            exit 1
+          fi
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
   generate-changelog:
     needs: get-version
